/**
 * Realistic Mock Data for SchoolERP
 * Follows PRD specifications and Indian school conventions.
 */

export const INITIAL_SCHOOL_SETTINGS = {
  schoolName: 'Greenwood Academy',
  schoolCode: 'GA-MUM-2024',
  academicYear: '2024-25',
  currentTerm: 'Term 2',
  affiliation: 'CBSE Affiliation #1130492',
  campus: 'Greenwood Campus, Bandra West',
  address: '14, Silver Oak Marg, Bandra West, Mumbai, Maharashtra 400050',
  phone: '+91 98201 44821',
  email: 'admin@greenwood.edu.in',
  principalName: 'Dr. Anjali Sharma',
  adminEmail: 'admin@greenwood.edu.in',
  currency: '₹',
};

export const INITIAL_CLASSES = [
  { id: 'c1', name: 'Nursery', section: 'A', academicYear: '2024-25', teacher: 'Mrs. Sunita Rao', capacity: 30, status: 'Active' },
  { id: 'c2', name: 'Junior KG', section: 'A', academicYear: '2024-25', teacher: 'Mrs. Rohini Sen', capacity: 30, status: 'Active' },
  { id: 'c3', name: 'Senior KG', section: 'A', academicYear: '2024-25', teacher: 'Ms. Neha Gupta', capacity: 32, status: 'Active' },
  { id: 'c4', name: 'Class I', section: 'A', academicYear: '2024-25', teacher: 'Mrs. Kavita Nair', capacity: 35, status: 'Active' },
  { id: 'c5', name: 'Class IV', section: 'A', academicYear: '2024-25', teacher: 'Mr. Arvind Deshmukh', capacity: 35, status: 'Active' },
  { id: 'c6', name: 'Class V', section: 'B', academicYear: '2024-25', teacher: 'Mrs. Meenakshi Soni', capacity: 38, status: 'Active' },
  { id: 'c7', name: 'Class VI', section: 'C', academicYear: '2024-25', teacher: 'Mr. Rajesh Kulkarni', capacity: 40, status: 'Active' },
  { id: 'c8', name: 'Class VIII', section: 'A', academicYear: '2024-25', teacher: 'Mr. Sandeep Mukherjee', capacity: 42, status: 'Active' },
  { id: 'c9', name: 'Class IX', section: 'B', academicYear: '2024-25', teacher: 'Mrs. Deepa Iyer', capacity: 40, status: 'Active' },
  { id: 'c10', name: 'Class X', section: 'A', academicYear: '2024-25', teacher: 'Dr. Rameshwar Bhat', capacity: 38, status: 'Active' },
  { id: 'c11', name: 'Class X', section: 'C', academicYear: '2024-25', teacher: 'Mrs. Vandana Shah', capacity: 38, status: 'Active' },
  { id: 'c12', name: 'Class VII', section: 'B (Archived)', academicYear: '2023-24', teacher: 'Mr. Vivek Chhabra', capacity: 35, status: 'Inactive' },
];

export const INITIAL_PARENTS = [
  { id: 'p1', name: 'Rajesh Mehta', phone: '+91 98201 44821', email: 'rajesh.mehta@example.com', address: '402, Lotus Towers, Andheri West, Mumbai', occupation: 'Chartered Accountant' },
  { id: 'p2', name: 'Vikram Patel', phone: '+91 98192 33410', email: 'vikram.patel@example.com', address: 'B-12, Palm Meadows, Juhu, Mumbai', occupation: 'Architect' },
  { id: 'p3', name: 'Sunil Sharma', phone: '+91 98330 91823', email: 'sunil.sharma@example.com', address: '101, Green Heights, Vile Parle East, Mumbai', occupation: 'Software Consultant' },
  { id: 'p4', name: 'Amit Verma', phone: '+91 98675 22091', email: 'amit.verma@example.com', address: '703, Sunrise Enclave, Powai, Mumbai', occupation: 'Bank Manager' },
  { id: 'p5', name: 'Ganesh Iyer', phone: '+91 99204 88712', email: 'ganesh.iyer@example.com', address: '12, Shanti Baug, Chembur, Mumbai', occupation: 'Civil Engineer' },
  { id: 'p6', name: 'Manoj Patil', phone: '+91 98701 55620', email: 'manoj.patil@example.com', address: '504, Windsor Bay, Bandra West, Mumbai', occupation: 'Business Owner' },
  { id: 'p7', name: 'Shekhar Kulkarni', phone: '+91 98110 33499', email: 'shekhar.kulkarni@example.com', address: '302, Sai Sagar, Dadar West, Mumbai', occupation: 'Professor' },
  { id: 'p8', name: 'Pramod Joshi', phone: '+91 97690 11458', email: 'pramod.joshi@example.com', address: 'A-104, Blue Ridge, Santacruz, Mumbai', occupation: 'Doctor' },
  { id: 'p9', name: 'Krishnan Nair', phone: '+91 98212 99014', email: 'krishnan.nair@example.com', address: '801, Sea View Apartments, Worli, Mumbai', occupation: 'HR Director' },
  { id: 'p10', name: 'Pradeep Desai', phone: '+91 98920 44512', email: 'pradeep.desai@example.com', address: '202, Royal Residency, Khar West, Mumbai', occupation: 'Exporter' },
];

export const INITIAL_STUDENTS = [
  {
    id: 's1',
    studentId: 'STU-2024-001',
    firstName: 'Aryan',
    lastName: 'Mehta',
    dob: '2011-08-14',
    gender: 'Male',
    admissionDate: '2022-06-15',
    classId: 'c8',
    className: 'Class VIII',
    section: 'A',
    rollNo: '18',
    parentId: 'p1',
    parentName: 'Rajesh Mehta',
    parentPhone: '+91 98201 44821',
    address: '402, Lotus Towers, Andheri West, Mumbai',
    status: 'Active',
    totalFee: 24000,
    paidFee: 12000,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDO8K2eT6RtOn3yCZRCrpEOTxMQSEcQmdkuhc1DCfDN6Qpa4duRFKT7wd3oFAXi0Bpo84sUr2bfljRZi_tahBI4erVzGv0cHWqijnJGNhrN4BJrz-8WT5i-579P6outSmaDZp5n2TYd056Q4hFwiaH_E-AZHqOfD5afy_Sv79xlu1W0nsQCJHm3AhkdZdvhEbyqiiAhyPyzDQaRvn7sx0H-O6eL9JBB90JQTNciDVEjTh3SMWzMZQ_c',
    attendanceRate: 94.5,
  },
  {
    id: 's2',
    studentId: 'STU-2024-002',
    firstName: 'Aarav',
    lastName: 'Patel',
    dob: '2010-05-20',
    gender: 'Male',
    admissionDate: '2021-06-10',
    classId: 'c9',
    className: 'Class IX',
    section: 'B',
    rollNo: '04',
    parentId: 'p2',
    parentName: 'Vikram Patel',
    parentPhone: '+91 98192 33410',
    address: 'B-12, Palm Meadows, Juhu, Mumbai',
    status: 'Active',
    totalFee: 26000,
    paidFee: 26000,
    avatar: null,
    attendanceRate: 96.0,
  },
  {
    id: 's3',
    studentId: 'STU-2024-003',
    firstName: 'Diya',
    lastName: 'Sharma',
    dob: '2015-11-03',
    gender: 'Female',
    admissionDate: '2023-06-12',
    classId: 'c5',
    className: 'Class IV',
    section: 'A',
    rollNo: '11',
    parentId: 'p3',
    parentName: 'Sunil Sharma',
    parentPhone: '+91 98330 91823',
    address: '101, Green Heights, Vile Parle East, Mumbai',
    status: 'Active',
    totalFee: 22000,
    paidFee: 14000,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBjp0qsm3c_FGkmsipNp40cUTlqymXwdTFg56uXkpDavcWAAr6eOkStgKSLPuLUKTrodn4sVcErgt3N4IFwF1nchCt896d-HhhqPlCR5wg5GSvtouSVHuHQtd6tmP_m5RXjWQq2TeFXTRFvfRUb0VSUEyjGY2o02cyfOvET0TDWTAJOMbtyf00Yn2vWMU78VVri3HyceDNwg-vIiCLW0k49Kwk-38HSS-tlxUgHpzfHWQH3NUsg__nE',
    attendanceRate: 98.2,
  },
  {
    id: 's4',
    studentId: 'STU-2024-004',
    firstName: 'Rohan',
    lastName: 'Verma',
    dob: '2009-02-18',
    gender: 'Male',
    admissionDate: '2020-06-15',
    classId: 'c10',
    className: 'Class X',
    section: 'A',
    rollNo: '24',
    parentId: 'p4',
    parentName: 'Amit Verma',
    parentPhone: '+91 98675 22091',
    address: '703, Sunrise Enclave, Powai, Mumbai',
    status: 'Active',
    totalFee: 30000,
    paidFee: 30000,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDiD1I8a2EE7QMZ_ryBeL1pFKltHr2OaD49WpFkhFJTKRgRPs4oW8O45-EWPGXCJq5aWbuCaV7um2oDmcXO6u6B8wa2ftzt8yurt8VcSgkUuoXBHJU3eqlF-AVDI1tZBE352jLVHOtU0KWVr5GqfHecR8zAJSjTOtMsP6lFcG2KD-lLm_eZIGbTpsSfWfP6Kc_gpW1YB5HMdBzR-MQ56mS3D1li7nAqQSv1EuQfmiCqbHt42i7UGkR',
    attendanceRate: 92.0,
  },
  {
    id: 's5',
    studentId: 'STU-2024-005',
    firstName: 'Ananya',
    lastName: 'Iyer',
    dob: '2013-09-27',
    gender: 'Female',
    admissionDate: '2022-06-20',
    classId: 'c7',
    className: 'Class VI',
    section: 'C',
    rollNo: '08',
    parentId: 'p5',
    parentName: 'Ganesh Iyer',
    parentPhone: '+91 99204 88712',
    address: '12, Shanti Baug, Chembur, Mumbai',
    status: 'Active',
    totalFee: 24000,
    paidFee: 17500,
    avatar: null,
    attendanceRate: 95.0,
  },
  {
    id: 's6',
    studentId: 'STU-2024-006',
    firstName: 'Anaya',
    lastName: 'Patil',
    dob: '2020-04-12',
    gender: 'Female',
    admissionDate: '2024-04-05',
    classId: 'c2',
    className: 'Junior KG',
    section: 'A',
    rollNo: '02',
    parentId: 'p6',
    parentName: 'Manoj Patil',
    parentPhone: '+91 98701 55620',
    address: '504, Windsor Bay, Bandra West, Mumbai',
    status: 'Active',
    totalFee: 30000,
    paidFee: 20000,
    avatar: null,
    attendanceRate: 97.4,
  },
  {
    id: 's7',
    studentId: 'STU-2024-007',
    firstName: 'Vivaan',
    lastName: 'Kulkarni',
    dob: '2021-01-22',
    gender: 'Male',
    admissionDate: '2024-04-05',
    classId: 'c1',
    className: 'Nursery',
    section: 'A',
    rollNo: '15',
    parentId: 'p7',
    parentName: 'Shekhar Kulkarni',
    parentPhone: '+91 98110 33499',
    address: '302, Sai Sagar, Dadar West, Mumbai',
    status: 'Active',
    totalFee: 28000,
    paidFee: 28000,
    avatar: null,
    attendanceRate: 93.0,
  },
  {
    id: 's8',
    studentId: 'STU-2024-008',
    firstName: 'Myra',
    lastName: 'Joshi',
    dob: '2019-07-19',
    gender: 'Female',
    admissionDate: '2023-04-08',
    classId: 'c3',
    className: 'Senior KG',
    section: 'A',
    rollNo: '19',
    parentId: 'p8',
    parentName: 'Pramod Joshi',
    parentPhone: '+91 97690 11458',
    address: 'A-104, Blue Ridge, Santacruz, Mumbai',
    status: 'Active',
    totalFee: 30000,
    paidFee: 15000,
    avatar: null,
    attendanceRate: 98.0,
  },
  {
    id: 's9',
    studentId: 'STU-2024-009',
    firstName: 'Pooja',
    lastName: 'Nair',
    dob: '2016-03-30',
    gender: 'Female',
    admissionDate: '2023-06-10',
    classId: 'c4',
    className: 'Class I',
    section: 'A',
    rollNo: '21',
    parentId: 'p9',
    parentName: 'Krishnan Nair',
    parentPhone: '+91 98212 99014',
    address: '801, Sea View Apartments, Worli, Mumbai',
    status: 'Active',
    totalFee: 20000,
    paidFee: 12500,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUECiq-GGyglCsPjVqkIj-0ODbz6b_dGPPfxIq4lQiRUe454YsHjY4OqXnv6-MmZVlVVeLOi3l_i1oNludKlQCcaRmdLcscHn7blAGQzoL4T4DYnrBfMxZj-TMUKBaOa56vXiPYQlQpuUBPxFTBs-qTm8_7XDig9E7WG61hf6MCTqLLV9X4dvRWkQ0CP5IFuqaWybvgoUPvqYarTWWvD6vFYppkGXjO4-77XzqdrmxJQX5zWdyR8JS',
    attendanceRate: 99.0,
  },
  {
    id: 's10',
    studentId: 'STU-2024-010',
    firstName: 'Rohan',
    lastName: 'Desai',
    dob: '2009-08-11',
    gender: 'Male',
    admissionDate: '2020-06-15',
    classId: 'c11',
    className: 'Class X',
    section: 'C',
    rollNo: '14',
    parentId: 'p10',
    parentName: 'Pradeep Desai',
    parentPhone: '+91 98920 44512',
    address: '202, Royal Residency, Khar West, Mumbai',
    status: 'Active',
    totalFee: 30000,
    paidFee: 30000,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDiD1I8a2EE7QMZ_ryBeL1pFKltHr2OaD49WpFkhFJTKRgRPs4oW8O45-EWPGXCJq5aWbuCaV7um2oDmcXO6u6B8wa2ftzt8yurt8VcSgkUuoXBHJU3eqlF-AVDI1tZBE352jLVHOtU0KWVr5GqfHecR8zAJSjTOtMsP6lFcG2KD-lLm_eZIGbTpsSfWfP6Kc_gpW1YB5HMdBzR-MQ56mS3D1li7nAqQSv1EuQfmiCqbHt42i7UGkR',
    attendanceRate: 91.5,
  },
  {
    id: 's11',
    studentId: 'STU-2024-011',
    firstName: 'Tanvi',
    lastName: 'Choudhary',
    dob: '2014-06-04',
    gender: 'Female',
    admissionDate: '2022-06-18',
    classId: 'c6',
    className: 'Class V',
    section: 'B',
    rollNo: '31',
    parentId: 'p1',
    parentName: 'Rajesh Mehta',
    parentPhone: '+91 98201 44821',
    address: '402, Lotus Towers, Andheri West, Mumbai',
    status: 'Inactive',
    totalFee: 22000,
    paidFee: 22000,
    avatar: null,
    attendanceRate: 88.0,
  },
];

export const INITIAL_FEE_STRUCTURES = [
  { id: 'fs1', classId: 'c1', className: 'Nursery', academicYear: '2024-25', annualFee: 28000, termFee: 14000, status: 'Active' },
  { id: 'fs2', classId: 'c2', className: 'Junior KG', academicYear: '2024-25', annualFee: 30000, termFee: 15000, status: 'Active' },
  { id: 'fs3', classId: 'c3', className: 'Senior KG', academicYear: '2024-25', annualFee: 30000, termFee: 15000, status: 'Active' },
  { id: 'fs4', classId: 'c4', className: 'Class I', academicYear: '2024-25', annualFee: 20000, termFee: 10000, status: 'Active' },
  { id: 'fs5', classId: 'c5', className: 'Class IV', academicYear: '2024-25', annualFee: 22000, termFee: 11000, status: 'Active' },
  { id: 'fs6', classId: 'c6', className: 'Class V', academicYear: '2024-25', annualFee: 22000, termFee: 11000, status: 'Active' },
  { id: 'fs7', classId: 'c7', className: 'Class VI', academicYear: '2024-25', annualFee: 24000, termFee: 12000, status: 'Active' },
  { id: 'fs8', classId: 'c8', className: 'Class VIII', academicYear: '2024-25', annualFee: 24000, termFee: 12000, status: 'Active' },
  { id: 'fs9', classId: 'c9', className: 'Class IX', academicYear: '2024-25', annualFee: 26000, termFee: 13000, status: 'Active' },
  { id: 'fs10', classId: 'c10', className: 'Class X', academicYear: '2024-25', annualFee: 30000, termFee: 15000, status: 'Active' },
];

export const INITIAL_PAYMENTS = [
  {
    id: 'pay1',
    receiptNo: 'REC-2024-089',
    studentId: 's2',
    studentName: 'Aarav Patel',
    className: 'Class IX-B',
    amount: 12500,
    date: '2024-10-24T11:40:00.000Z',
    mode: 'UPI',
    referenceNo: 'UPI/402918491029',
    status: 'Completed',
    remarks: 'Term 2 Fee cleared',
  },
  {
    id: 'pay2',
    receiptNo: 'REC-2024-088',
    studentId: 's3',
    studentName: 'Diya Sharma',
    className: 'Class IV-A',
    amount: 8000,
    date: '2024-10-24T10:45:00.000Z',
    mode: 'Cash',
    referenceNo: 'CASH-COUNTER-01',
    status: 'Completed',
    remarks: 'Installment 1 paid by father',
  },
  {
    id: 'pay3',
    receiptNo: 'REC-2024-087',
    studentId: 's4',
    studentName: 'Rohan Verma',
    className: 'Class X-A',
    amount: 15000,
    date: '2024-10-24T09:30:00.000Z',
    mode: 'Cheque',
    referenceNo: 'Chq #492810 (HDFC Bank)',
    status: 'Completed',
    remarks: 'Annual balance settlement',
  },
  {
    id: 'pay4',
    receiptNo: 'REC-2024-086',
    studentId: 's5',
    studentName: 'Ananya Iyer',
    className: 'Class VI-C',
    amount: 6500,
    date: '2024-10-24T08:15:00.000Z',
    mode: 'UPI',
    referenceNo: 'UPI/402819827101',
    status: 'Completed',
    remarks: 'Tuition fee component',
  },
  {
    id: 'pay5',
    receiptNo: 'REC-2024-085',
    studentId: 's10',
    studentName: 'Rohan Desai',
    className: 'Class X-C',
    amount: 15000,
    date: '2024-10-23T14:20:00.000Z',
    mode: 'UPI',
    referenceNo: 'UPI/402711823901',
    status: 'Completed',
    remarks: 'Class X board & tuition',
  },
  {
    id: 'pay6',
    receiptNo: 'REC-2024-084',
    studentId: 's9',
    studentName: 'Pooja Nair',
    className: 'Class I-A',
    amount: 7500,
    date: '2024-10-23T11:10:00.000Z',
    mode: 'Cheque',
    referenceNo: 'Chq #102911 (SBI)',
    status: 'Completed',
    remarks: 'Mid-term installment',
  },
];

export const INITIAL_ATTENDANCE_RECORDS = [
  // Today's attendance records
  { id: 'att1', studentId: 's1', studentName: 'Aryan Mehta', classId: 'c8', className: 'Class VIII-A', date: '2024-10-24', status: 'Present' },
  { id: 'att2', studentId: 's2', studentName: 'Aarav Patel', classId: 'c9', className: 'Class IX-B', date: '2024-10-24', status: 'Present' },
  { id: 'att3', studentId: 's3', studentName: 'Diya Sharma', classId: 'c5', className: 'Class IV-A', date: '2024-10-24', status: 'Present' },
  { id: 'att4', studentId: 's4', studentName: 'Rohan Verma', classId: 'c10', className: 'Class X-A', date: '2024-10-24', status: 'Absent' },
  { id: 'att5', studentId: 's5', studentName: 'Ananya Iyer', classId: 'c7', className: 'Class VI-C', date: '2024-10-24', status: 'Present' },
  { id: 'att6', studentId: 's6', studentName: 'Anaya Patil', classId: 'c2', className: 'Junior KG-A', date: '2024-10-24', status: 'Present' },
  { id: 'att7', studentId: 's7', studentName: 'Vivaan Kulkarni', classId: 'c1', className: 'Nursery-A', date: '2024-10-24', status: 'Present' },
  { id: 'att8', studentId: 's8', studentName: 'Myra Joshi', classId: 'c3', className: 'Senior KG-A', date: '2024-10-24', status: 'Present' },
  { id: 'att9', studentId: 's9', studentName: 'Pooja Nair', classId: 'c4', className: 'Class I-A', date: '2024-10-24', status: 'Present' },
  { id: 'att10', studentId: 's10', studentName: 'Rohan Desai', classId: 'c11', className: 'Class X-C', date: '2024-10-24', status: 'Present' },
];

/**
 * Storage helper for local state persistence
 */
const STORAGE_KEYS = {
  SETTINGS: 'schoolerp_settings',
  CLASSES: 'schoolerp_classes',
  PARENTS: 'schoolerp_parents',
  STUDENTS: 'schoolerp_students',
  FEES: 'schoolerp_fee_structures',
  PAYMENTS: 'schoolerp_payments',
  ATTENDANCE: 'schoolerp_attendance',
};

export const getStored = (key, fallback) => {
  try {
    const item = localStorage.getItem(key);
    return item ? JSON.parse(item) : fallback;
  } catch {
    return fallback;
  }
};

export const setStored = (key, data) => {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (err) {
    console.warn('LocalStorage error:', err);
  }
};

export const resetToDefaults = () => {
  setStored(STORAGE_KEYS.SETTINGS, INITIAL_SCHOOL_SETTINGS);
  setStored(STORAGE_KEYS.CLASSES, INITIAL_CLASSES);
  setStored(STORAGE_KEYS.PARENTS, INITIAL_PARENTS);
  setStored(STORAGE_KEYS.STUDENTS, INITIAL_STUDENTS);
  setStored(STORAGE_KEYS.FEES, INITIAL_FEE_STRUCTURES);
  setStored(STORAGE_KEYS.PAYMENTS, INITIAL_PAYMENTS);
  setStored(STORAGE_KEYS.ATTENDANCE, INITIAL_ATTENDANCE_RECORDS);
};

export { STORAGE_KEYS };
